#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2019

environment:  
  major: 2
  minor: 0
  patch: 0


# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true
  - ps: |
      $isCI = $Env:APPVEYOR_REPO_TAG -eq $false
      $isBranch = $isCI -and ($Env:APPVEYOR_REPO_BRANCH -ne 'master')
      $branchTag = "$(if ($isBranch) { $Env:APPVEYOR_REPO_BRANCH + '-' } else { $null })"
      $Env:VersionPrefix = "$($Env:major).$($Env:minor).$($Env:patch)"
      $Env:VersionSuffix = "$(if ($isCI) { $branchTag + 'CI' + $Env:APPVEYOR_BUILD_NUMBER } else { $null })"
      $Env:SemanticVersion = "$($Env:VersionPrefix)$(if ($isCI) { '-' } else { $null })$($Env:VersionSuffix)"
      appveyor UpdateBuild -Version $Env:SemanticVersion

#---------------------------------#
#       build configuration       #
#---------------------------------#

install:
  - ps: |
      $nugetPath = "$($Env:SYSTEMDRIVE)\Tools\NuGet"
      (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', "$($nugetPath)\nuget.exe")

cache:
  - $nugetPath


# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  - cd src
  - dotnet restore

build:
  verbosity: minimal               # MSBuild verbosity level

# create meta package
after_build:
  - ps: |
      & $nugetPath\nuget.exe pack $Env:APPVEYOR_BUILD_FOLDER\src\FluentFiles.nuspec -Properties "version=$($Env:APPVEYOR_BUILD_VERSION);year=$(Get-Date –f yyyy)"   

nuget:
  project_feed: true
  disable_publish_on_pr: true

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - ps: Get-ChildItem *.Tests | % { cd $_; dotnet test --configuration $Env:CONFIGURATION --no-build; cd ..; }


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    on:
      appveyor_repo_tag: true
    server: # nuget.org
    api_key:
      secure: mywsHL6tvVk7YjYZDmG093BJ/1uRQ/+xcF6EFQXiyoGta5N/i2d5Dk0kQYHP7FXA
    skip_symbols: false
    symbol_server: # SymbolSource.org
    artifact: /.*\.nupkg/